------------------------------------------------------------
-- AltTracker BiS Data
-- Best-in-Slot gear lists per class/spec/tier for TBC.
--
-- Structure:
--   AltTracker.BisData[CLASS_FILE][SpecTalentName][Tier][slotKey]
--   - CLASS_FILE : uppercase class token (matches UnitClass)
--   - SpecTalentName : talent tab name (matches GetTalentTabInfo)
--   - Tier : "T4", "T5", "T6", "Sunwell"
--   - slotKey : gear slot key (head, neck, shoulder, back,
--               chest, wrist, hands, waist, legs, feet,
--               ring1, ring2, trinket1, trinket2,
--               mainhand, offhand, ranged)
--
-- Values can be a single item name (string) or a table of
-- acceptable alternatives (for ring/trinket swaps, etc.).
-- Item names must match GetItemInfo() output exactly.
--
-- This data is static and will never change for TBC Classic.
-- Sources: wowtbc.gg, wowhead TBC guides.
------------------------------------------------------------

AltTracker = AltTracker or {}

AltTracker.BisData = {

------------------------------------------------------------
-- DRUID
------------------------------------------------------------
["DRUID"] = {
    ["Balance"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Brooch of Unquenchable Fury",
            shoulder = "Mantle of the Mind Flayer",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Wrath of Spellfire",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Aldor",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Ashyen's Gift"},
            ring2    = {"Ring of Recurrence", "Ashyen's Gift"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "Idol of the Raven Goddess",
        },
        T5 = {
            head     = "Nordrassil Headpiece",
            neck     = "Brooch of Unquenchable Fury",
            shoulder = "Nordrassil Wrath-Mantle",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Nordrassil Chestpiece",
            wrist    = "Bracers of Havok",
            hands    = "Nordrassil Gauntlets",
            waist    = "Belt of Blasting",
            legs     = "Nordrassil Wrath-Kilt",
            feet     = "Boots of Blasting",
            ring1    = {"Ring of Endless Coils", "Band of Al'ar"},
            ring2    = {"Ring of Endless Coils", "Band of Al'ar"},
            trinket1 = {"Icon of the Silver Crescent", "The Lightning Capacitor"},
            trinket2 = {"Icon of the Silver Crescent", "The Lightning Capacitor"},
            mainhand = "The Nexus Key",
            offhand  = "Chronicle of Dark Secrets",
            ranged   = "Idol of the Raven Goddess",
        },
        T6 = {
            head     = "Thunderheart Cover",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Thunderheart Shoulderpads",
            back     = "Tattered Cape of Antonidas",
            chest    = "Thunderheart Vest",
            wrist    = "Bracers of Nimble Thought",
            hands    = "Thunderheart Gauntlets",
            waist    = "Belt of Blasting",
            legs     = "Thunderheart Pants",
            feet     = "Boots of Blasting",
            ring1    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            ring2    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            trinket1 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            trinket2 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            mainhand = "Zhar'doom, Greatstaff of the Devourer",
            offhand  = nil,
            ranged   = "Idol of the Raven Goddess",
        },
        Sunwell = {
            head     = "Thunderheart Cover",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Thunderheart Shoulderpads",
            back     = "Tattered Cape of Antonidas",
            chest    = "Sunfire Robe",
            wrist    = "Bracers of the Tempest",
            hands    = "Sunfire Handwraps",
            waist    = "Belt of Blasting",
            legs     = "Thunderheart Pants",
            feet     = "Boots of Blasting",
            ring1    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            ring2    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            trinket1 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            trinket2 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            mainhand = "Zhar'doom, Greatstaff of the Devourer",
            offhand  = nil,
            ranged   = "Idol of the Raven Goddess",
        },
    },
    ["Feral Combat"] = {
        T4 = {
            head     = "Stag-Helm of Malorne",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Mantle of Shadowy Embrace",
            back     = "Drape of the Dark Reavers",
            chest    = "Chestguard of the Conniver",
            wrist    = "Bracers of Maliciousness",
            hands    = "Gloves of Dexterous Manipulation",
            waist    = "Belt of Deep Shadow",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Earthwarden",
            offhand  = nil,
            ranged   = "Idol of Terror",
        },
        T5 = {
            head     = "Nordrassil Headdress",
            neck     = "Telonicus's Pendant of Mayhem",
            shoulder = "Nordrassil Feral-Mantle",
            back     = "Drape of Dark Reavers",
            chest    = "Nordrassil Chestplate",
            wrist    = "Bracers of the Hunt",
            hands    = "Nordrassil Handgrips",
            waist    = "Belt of One-Hundred Deaths",
            legs     = "Nordrassil Feral-Kilt",
            feet     = "Boots of Natural Grace",
            ring1    = {"Ring of a Thousand Marks", "Ring of Lethality"},
            ring2    = {"Ring of a Thousand Marks", "Ring of Lethality"},
            trinket1 = {"Dragonspine Trophy", "Bloodlust Brooch"},
            trinket2 = {"Dragonspine Trophy", "Bloodlust Brooch"},
            mainhand = "Staff of the Leviathan",
            offhand  = nil,
            ranged   = "Idol of Terror",
        },
        T6 = {
            head     = "Thunderheart Headguard",
            neck     = "Pendant of Titans",
            shoulder = "Thunderheart Pauldrons",
            back     = "Shadowmoon Destroyer's Drape",
            chest    = "Thunderheart Chestguard",
            wrist    = "Insidious Bands",
            hands    = "Thunderheart Handguards",
            waist    = "Belt of Natural Power",
            legs     = "Thunderheart Leggings",
            feet     = "Footwraps of Wild Encroachment",
            ring1    = {"Stormrage Signet Ring", "Band of the Eternal Champion"},
            ring2    = {"Stormrage Signet Ring", "Band of the Eternal Champion"},
            trinket1 = {"Dragonspine Trophy", "Berserker's Call"},
            trinket2 = {"Dragonspine Trophy", "Berserker's Call"},
            mainhand = "Staff of Immaculate Recovery",
            offhand  = nil,
            ranged   = "Idol of Terror",
        },
        Sunwell = {
            head     = "Thunderheart Headguard",
            neck     = "Hard Khorium Choker",
            shoulder = "Thunderheart Pauldrons",
            back     = "Shadowmoon Destroyer's Drape",
            chest    = "Thunderheart Chestguard",
            wrist    = "Insidious Bands",
            hands    = "Thunderheart Handguards",
            waist    = "Belt of Natural Power",
            legs     = "Thunderheart Leggings",
            feet     = "Footwraps of Wild Encroachment",
            ring1    = {"Stormrage Signet Ring", "Hard Khorium Band"},
            ring2    = {"Stormrage Signet Ring", "Hard Khorium Band"},
            trinket1 = {"Dragonspine Trophy", "Shard of Contempt"},
            trinket2 = {"Dragonspine Trophy", "Shard of Contempt"},
            mainhand = "Staff of Immaculate Recovery",
            offhand  = nil,
            ranged   = "Idol of Terror",
        },
    },
    ["Feral Combat (Bear)"] = {
        -- Tank-oriented BiS for Bear-specced Feral Druids.
        T4 = {
            head     = "Stag-Helm of Malorne",
            neck     = "Teeth of Gruul",
            shoulder = "Mantle of Shadowy Embrace",
            back     = "Slikk's Cloak of Placation",
            chest    = "Chestguard of the Conniver",
            wrist    = "Heavy Clefthoof Bracers",
            hands    = "Heavy Clefthoof Gloves",
            waist    = "Girdle of the Fallen Crusader",
            legs     = "Skulker's Greaves",
            feet     = "Heavy Clefthoof Boots",
            ring1    = {"Ring of the Stalwart Protector", "Violet Signet of the Great Protector"},
            ring2    = {"Ring of the Stalwart Protector", "Violet Signet of the Great Protector"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Adamantine Figurine"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Adamantine Figurine"},
            mainhand = "Earthwarden",
            offhand  = nil,
            ranged   = "Idol of Brutality",
        },
        T5 = {
            head     = "Nordrassil Headdress",
            neck     = "Brooch of Deftness",
            shoulder = "Nordrassil Feral-Mantle",
            back     = "Slikk's Cloak of Placation",
            chest    = "Nordrassil Chestplate",
            wrist    = "Bands of Nefarious Deeds",
            hands    = "Nordrassil Handgrips",
            waist    = "Belt of Natural Power",
            legs     = "Nordrassil Feral-Kilt",
            feet     = "Zierhut's Lost Treads",
            ring1    = {"Ring of the Stalwart Protector", "Violet Signet of the Great Protector"},
            ring2    = {"Ring of the Stalwart Protector", "Violet Signet of the Great Protector"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Alchemist's Stone"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Alchemist's Stone"},
            mainhand = "Wildfury Greatstaff",
            offhand  = nil,
            ranged   = "Idol of Brutality",
        },
        T6 = {
            head     = "Thunderheart Headguard",
            neck     = "Pendant of Titans",
            shoulder = "Thunderheart Pauldrons",
            back     = "Shadowmoon Destroyer's Drape",
            chest    = "Thunderheart Chestguard",
            wrist    = "Bindings of Lightning Reflexes",
            hands    = "Thunderheart Handguards",
            waist    = "Belt of Natural Power",
            legs     = "Thunderheart Leggings",
            feet     = "Boots of Utter Darkness",
            ring1    = {"Band of the Eternal Champion", "Ring of the Stalwart Protector"},
            ring2    = {"Band of the Eternal Champion", "Ring of the Stalwart Protector"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Badge of Tenacity"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Badge of Tenacity"},
            mainhand = "Wildfury Greatstaff",
            offhand  = nil,
            ranged   = "Idol of Brutality",
        },
        Sunwell = {
            head     = "Thunderheart Headguard",
            neck     = "Emberspur Talisman",
            shoulder = "Thunderheart Pauldrons",
            back     = "Shadowmoon Destroyer's Drape",
            chest    = "Thunderheart Chestguard",
            wrist    = "Bindings of Lightning Reflexes",
            hands    = "Thunderheart Handguards",
            waist    = "Belt of Natural Power",
            legs     = "Thunderheart Leggings",
            feet     = "Boots of Utter Darkness",
            ring1    = {"Hard Khorium Band", "Band of the Eternal Champion"},
            ring2    = {"Hard Khorium Band", "Band of the Eternal Champion"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Badge of Tenacity"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Badge of Tenacity"},
            mainhand = "Pillar of Ferocity",
            offhand  = nil,
            ranged   = "Idol of Brutality",
        },
    },
    ["Restoration"] = {
        T4 = {
            head     = "Stag-Helm of Malorne",
            neck     = "Teeth of Gruul",
            shoulder = "Pauldrons of the Solace-Giver",
            back     = "Stainless Cloak of the Pure Hearted",
            chest    = "Chestguard of Malorne",
            wrist    = "Bands of Nefarious Deeds",
            hands    = "Gloves of Saintly Blessings",
            waist    = "Cord of Nature's Sustenance",
            legs     = "Earthsoul Leggings",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            ring2    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            trinket1 = {"Essence of the Martyr", "Ribbon of Sacrifice"},
            trinket2 = {"Essence of the Martyr", "Ribbon of Sacrifice"},
            mainhand = "Light's Justice",
            offhand  = "Windcaller's Orb",
            ranged   = "Idol of the Emerald Queen",
        },
    },
},

------------------------------------------------------------
-- HUNTER
------------------------------------------------------------
["HUNTER"] = {
    ["Beast Mastery"] = {
        T4 = {
            head     = "Beast Lord Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Beast Lord Mantle",
            back     = "Vengeance Wrap",
            chest    = "Beast Lord Cuirass",
            wrist    = "Vambraces of Ending",
            hands    = "Beast Lord Handguards",
            waist    = "Girdle of Treachery",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Sunfury Bow of the Phoenix",
            offhand  = nil,
            ranged   = "Sunfury Bow of the Phoenix",
        },
    },
    ["Marksmanship"] = {
        T4 = {
            head     = "Beast Lord Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Beast Lord Mantle",
            back     = "Vengeance Wrap",
            chest    = "Beast Lord Cuirass",
            wrist    = "Vambraces of Ending",
            hands    = "Beast Lord Handguards",
            waist    = "Girdle of Treachery",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Sunfury Bow of the Phoenix",
            offhand  = nil,
            ranged   = "Sunfury Bow of the Phoenix",
        },
    },
    ["Survival"] = {
        T4 = {
            head     = "Beast Lord Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Beast Lord Mantle",
            back     = "Vengeance Wrap",
            chest    = "Beast Lord Cuirass",
            wrist    = "Vambraces of Ending",
            hands    = "Beast Lord Handguards",
            waist    = "Girdle of Treachery",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Sunfury Bow of the Phoenix",
            offhand  = nil,
            ranged   = "Sunfury Bow of the Phoenix",
        },
    },
},

------------------------------------------------------------
-- MAGE
------------------------------------------------------------
["MAGE"] = {
    ["Arcane"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Pauldrons of the Aldor",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Chestguard of the Conniver",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Aldor",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "Scryer's Bloodgem",
        },
    },
    ["Fire"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Pauldrons of the Aldor",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Wrath of Spellfire",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Aldor",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "Scryer's Bloodgem",
        },
    },
    ["Frost"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Pauldrons of the Aldor",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Wrath of Spellfire",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Aldor",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "Scryer's Bloodgem",
        },
    },
},

------------------------------------------------------------
-- PALADIN
------------------------------------------------------------
["PALADIN"] = {
    ["Holy"] = {
        T4 = {
            head     = "Justicar Crown",
            neck     = "Teeth of Gruul",
            shoulder = "Justicar Shoulderplates",
            back     = "Stainless Cloak of the Pure Hearted",
            chest    = "Justicar Chestpiece",
            wrist    = "Bindings of the Timewalker",
            hands    = "Justicar Gloves",
            waist    = "Cord of Nature's Sustenance",
            legs     = "Pantaloons of Repentance",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            ring2    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            trinket1 = {"Essence of the Martyr", "Eye of Gruul"},
            trinket2 = {"Essence of the Martyr", "Eye of Gruul"},
            mainhand = "Light's Justice",
            offhand  = "Mazthoril Honor Shield",
            ranged   = "Eredar Wand of Obliteration",
        },
    },
    ["Protection"] = {
        T4 = {
            head     = "Justicar Faceguard",
            neck     = "Barbed Choker of Discipline",
            shoulder = "Justicar Shoulderguards",
            back     = "Gilded Thorium Cloak",
            chest    = "Justicar Breastplate",
            wrist    = "Bracers of the Green Fortress",
            hands    = "Iron Gauntlets of the Maiden",
            waist    = "Crimson Girdle of the Indomitable",
            legs     = "Timewarden's Leggings",
            feet     = "Boots of Elusion",
            ring1    = {"Elementium Band of the Sentry", "Ring of Unyielding Force"},
            ring2    = {"Elementium Band of the Sentry", "Ring of Unyielding Force"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Figurine - Living Ruby Serpent"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Figurine - Living Ruby Serpent"},
            mainhand = "Continuum Blade",
            offhand  = "Crest of the Sha'tar",
            ranged   = "Libram of Repentance",
        },
    },
    ["Retribution"] = {
        T4 = {
            head     = "Warbringer Battle-Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Warbringer Shoulderplates",
            back     = "Vengeance Wrap",
            chest    = "Warbringer Breastplate",
            wrist    = "Bladespire Warbands",
            hands    = "Gauntlets of Martial Perfection",
            waist    = "Girdle of the Endless Pit",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Gorehowl",
            offhand  = nil,
            ranged   = "Libram of Avengement",
        },
    },
},

------------------------------------------------------------
-- PRIEST  (T4 confirmed from wowtbc.gg scrape)
------------------------------------------------------------
["PRIEST"] = {
    ["Discipline"] = {
        T4 = {
            head     = "Light-Collar of the Incarnate",
            neck     = "Teeth of Gruul",
            shoulder = "Primal Mooncloth Shoulders",
            back     = "Stainless Cloak of the Pure Hearted",
            chest    = "Primal Mooncloth Robe",
            wrist    = "Bindings of the Timewalker",
            hands    = "Gloves of Saintly Blessings",
            waist    = "Primal Mooncloth Belt",
            legs     = "Pantaloons of Repentance",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            ring2    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            trinket1 = {"Essence of the Martyr", "Eye of Gruul"},
            trinket2 = {"Essence of the Martyr", "Eye of Gruul"},
            mainhand = "Light's Justice",
            offhand  = "Windcaller's Orb",
            ranged   = "Blue Diamond Witchwand",
        },
    },
    ["Holy"] = {
        -- T4 confirmed: wowtbc.gg scrape
        T4 = {
            head     = "Light-Collar of the Incarnate",
            neck     = "Teeth of Gruul",
            shoulder = "Primal Mooncloth Shoulders",
            back     = "Stainless Cloak of the Pure Hearted",
            chest    = "Primal Mooncloth Robe",
            wrist    = "Bindings of the Timewalker",
            hands    = "Gloves of Saintly Blessings",
            waist    = "Primal Mooncloth Belt",
            legs     = "Pantaloons of Repentance",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            ring2    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            trinket1 = {"Essence of the Martyr", "Eye of Gruul"},
            trinket2 = {"Essence of the Martyr", "Eye of Gruul"},
            mainhand = "Light's Justice",
            offhand  = "Windcaller's Orb",
            ranged   = "Blue Diamond Witchwand",
        },
        T5 = {
            head     = "Vestments of the Avatar",
            neck     = "Teeth of Gruul",
            shoulder = "Mantle of the Avatar",
            back     = "Bishop's Cloak",
            chest    = "Shroud of the Avatar",
            wrist    = "Cuffs of Devastation",
            hands    = "Handguards of the Avatar",
            waist    = "Belt of the Long Road",
            legs     = "Breeches of the Avatar",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Ring of Endless Coils"},
            ring2    = {"Jade Ring of the Everliving", "Ring of Endless Coils"},
            trinket1 = {"Essence of the Martyr", "Memento of Tyrande"},
            trinket2 = {"Essence of the Martyr", "Memento of Tyrande"},
            mainhand = "Light's Justice",
            offhand  = "Talisman of Nightbane",
            ranged   = "Blue Diamond Witchwand",
        },
        T6 = {
            head     = "Cowl of Absolution",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Amice of the Convoker",
            back     = "Shroud of the Highborne",
            chest    = "Vestments of Absolution",
            wrist    = "Bracers of Nimble Thought",
            hands    = "Handguards of Absolution",
            waist    = "Belt of the Long Road",
            legs     = "Pantaloons of Calming Strife",
            feet     = "Slippers of the Seacaller",
            ring1    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            ring2    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            trinket1 = {"Memento of Tyrande", "Direbrew Hops"},
            trinket2 = {"Memento of Tyrande", "Direbrew Hops"},
            mainhand = "Hammer of Judgement",
            offhand  = "Touch of Inspiration",
            ranged   = "Wand of the Demonsoul",
        },
        Sunwell = {
            head     = "Cowl of Light's Purity",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Shawl of Wonderment",
            back     = "Shroud of the Highborne",
            chest    = "Vestments of Absolution",
            wrist    = "Bracers of the Tempest",
            hands    = "Handguards of Absolution",
            waist    = "Belt of the Long Road",
            legs     = "Pantaloons of Calming Strife",
            feet     = "Slippers of the Seacaller",
            ring1    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            ring2    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            trinket1 = {"Memento of Tyrande", "Direbrew Hops"},
            trinket2 = {"Memento of Tyrande", "Direbrew Hops"},
            mainhand = "Hand of the Deceiver",
            offhand  = "Touch of Inspiration",
            ranged   = "Wand of the Demonsoul",
        },
    },
    ["Shadow"] = {
        -- T4 confirmed: wowtbc.gg scrape
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Ritssyn's Lost Pendant",
            shoulder = "Frozen Shadoweave Shoulders",
            back     = "Shadow-Cloak of Dalaran",
            chest    = "Frozen Shadoweave Robe",
            wrist    = "Bracers of Havok",
            hands    = "Soul-Eater's Handwraps",
            waist    = "Belt of Divine Inspiration",
            legs     = "Spellstrike Pants",
            feet     = "Frozen Shadoweave Boots",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "The Black Stalk",
        },
        T5 = {
            head     = "Hood of the Avatar",
            neck     = "Collar of Cho'gall",
            shoulder = "Shoulderguards of the Avatar",
            back     = "Shadow-Cloak of Dalaran",
            chest    = "Shroud of the Avatar",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Avatar",
            waist    = "Belt of Blasting",
            legs     = "Leggings of the Avatar",
            feet     = "Frozen Shadoweave Boots",
            ring1    = {"Ring of Endless Coils", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Endless Coils", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "The Lightning Capacitor"},
            trinket2 = {"Icon of the Silver Crescent", "The Lightning Capacitor"},
            mainhand = "The Nexus Key",
            offhand  = "Chronicle of Dark Secrets",
            ranged   = "The Black Stalk",
        },
        T6 = {
            head     = "Hood of Absolution",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Shoulderpads of Absolution",
            back     = "Tattered Cape of Antonidas",
            chest    = "Robe of Absolution",
            wrist    = "Bracers of Nimble Thought",
            hands    = "Gloves of Absolution",
            waist    = "Belt of Blasting",
            legs     = "Leggings of Channeled Elements",
            feet     = "Boots of Blasting",
            ring1    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            ring2    = {"Ring of Ancient Knowledge", "Band of the Eternal Sage"},
            trinket1 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            trinket2 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            mainhand = "Zhar'doom, Greatstaff of the Devourer",
            offhand  = nil,
            ranged   = "Wand of the Demonsoul",
        },
        Sunwell = {
            head     = "Hood of Absolution",
            neck     = "Amulet of Unfettered Magics",
            shoulder = "Shoulderpads of Absolution",
            back     = "Tattered Cape of Antonidas",
            chest    = "Robe of Absolution",
            wrist    = "Bracers of the Tempest",
            hands    = "Gloves of Absolution",
            waist    = "Belt of Blasting",
            legs     = "Leggings of Channeled Elements",
            feet     = "Boots of Blasting",
            ring1    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            ring2    = {"Ring of Ancient Knowledge", "Loop of Forged Deeds"},
            trinket1 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            trinket2 = {"The Skull of Gul'dan", "Hex Shrunken Head"},
            mainhand = "Zhar'doom, Greatstaff of the Devourer",
            offhand  = nil,
            ranged   = "Wand of the Demonsoul",
        },
    },
},

------------------------------------------------------------
-- ROGUE
------------------------------------------------------------
["ROGUE"] = {
    ["Combat"] = {
        T4 = {
            head     = "Netherblade Facemask",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Netherblade Shoulderpads",
            back     = "Drape of the Dark Reavers",
            chest    = "Netherblade Chestpiece",
            wrist    = "Vambraces of Ending",
            hands    = "Gloves of Dexterous Manipulation",
            waist    = "Girdle of Treachery",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Spiteblade",
            offhand  = "Latro's Shifting Sword",
            ranged   = "Consortium Blaster",
        },
    },
    ["Assassination"] = {
        T4 = {
            head     = "Netherblade Facemask",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Netherblade Shoulderpads",
            back     = "Drape of the Dark Reavers",
            chest    = "Netherblade Chestpiece",
            wrist    = "Vambraces of Ending",
            hands    = "Gloves of Dexterous Manipulation",
            waist    = "Girdle of Treachery",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Spiteblade",
            offhand  = "Latro's Shifting Sword",
            ranged   = "Consortium Blaster",
        },
    },
},

------------------------------------------------------------
-- SHAMAN
------------------------------------------------------------
["SHAMAN"] = {
    ["Elemental"] = {
        T4 = {
            head     = "Cyclone Faceguard",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Cyclone Shoulderguards",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Cyclone Chestguard",
            wrist    = "Bracers of Havok",
            hands    = "Cyclone Gloves",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "Totem of Wrath",
        },
    },
    ["Enhancement"] = {
        T4 = {
            head     = "Cataclysm Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Cataclysm Shoulderplates",
            back     = "Vengeance Wrap",
            chest    = "Cataclysm Chestplate",
            wrist    = "Bladespire Warbands",
            hands    = "Gauntlets of Martial Perfection",
            waist    = "Girdle of the Endless Pit",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Spiteblade",
            offhand  = "Latro's Shifting Sword",
            ranged   = "Totem of the Astral Winds",
        },
    },
    ["Restoration"] = {
        T4 = {
            head     = "Cyclone Headdress",
            neck     = "Teeth of Gruul",
            shoulder = "Cyclone Shoulderpads",
            back     = "Stainless Cloak of the Pure Hearted",
            chest    = "Cyclone Hauberk",
            wrist    = "Bindings of the Timewalker",
            hands    = "Cyclone Handguards",
            waist    = "Cord of Nature's Sustenance",
            legs     = "Pantaloons of Repentance",
            feet     = "Boots of the Incorrupt",
            ring1    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            ring2    = {"Jade Ring of the Everliving", "Violet Signet of the Grand Restorer"},
            trinket1 = {"Essence of the Martyr", "Eye of Gruul"},
            trinket2 = {"Essence of the Martyr", "Eye of Gruul"},
            mainhand = "Light's Justice",
            offhand  = "Windcaller's Orb",
            ranged   = "Totem of Healing Rains",
        },
    },
},

------------------------------------------------------------
-- WARLOCK
------------------------------------------------------------
["WARLOCK"] = {
    ["Affliction"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Ritssyn's Lost Pendant",
            shoulder = "Frozen Shadoweave Shoulders",
            back     = "Shadow-Cloak of Dalaran",
            chest    = "Frozen Shadoweave Robe",
            wrist    = "Bracers of Havok",
            hands    = "Soul-Eater's Handwraps",
            waist    = "Belt of Divine Inspiration",
            legs     = "Spellstrike Pants",
            feet     = "Frozen Shadoweave Boots",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "The Black Stalk",
        },
    },
    ["Demonology"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Voidheart Mantle",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Voidheart Robe",
            wrist    = "Bracers of Havok",
            hands    = "Voidheart Gloves",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "The Black Stalk",
        },
    },
    ["Destruction"] = {
        T4 = {
            head     = "Spellstrike Hood",
            neck     = "Adornment of Stolen Souls",
            shoulder = "Pauldrons of the Aldor",
            back     = "Ruby Drape of the Mysticant",
            chest    = "Wrath of Spellfire",
            wrist    = "Bracers of Havok",
            hands    = "Gloves of the Aldor",
            waist    = "Girdle of Ruination",
            legs     = "Spellstrike Pants",
            feet     = "Boots of Foretelling",
            ring1    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            ring2    = {"Ring of Recurrence", "Cobalt Band of Tyrigosa"},
            trinket1 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            trinket2 = {"Icon of the Silver Crescent", "Quagmirran's Eye"},
            mainhand = "Nathrezim Mindblade",
            offhand  = "Orb of the Soul-Eater",
            ranged   = "The Black Stalk",
        },
    },
},

------------------------------------------------------------
-- WARRIOR  (Fury T4 confirmed from wowtbc.gg scrape)
------------------------------------------------------------
["WARRIOR"] = {
    ["Arms"] = {
        T4 = {
            head     = "Warbringer Battle-Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Warbringer Shoulderplates",
            back     = "Vengeance Wrap",
            chest    = "Warbringer Breastplate",
            wrist    = "Bladespire Warbands",
            hands    = "Gauntlets of Martial Perfection",
            waist    = "Girdle of the Endless Pit",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Gorehowl",
            offhand  = nil,
            ranged   = "Sunfury Bow of the Phoenix",
        },
    },
    ["Fury"] = {
        -- T4 confirmed: wowtbc.gg scrape
        T4 = {
            head     = "Warbringer Battle-Helm",
            neck     = "Mithril Chain of Heroism",
            shoulder = "Warbringer Shoulderplates",
            back     = "Vengeance Wrap",
            chest    = "Warbringer Breastplate",
            wrist    = "Bladespire Warbands",
            hands    = "Gauntlets of Martial Perfection",
            waist    = "Girdle of the Endless Pit",
            legs     = "Skulker's Greaves",
            feet     = "Edgewalker Longboots",
            ring1    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            ring2    = {"Ring of a Thousand Marks", "Garona's Signet Ring"},
            trinket1 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            trinket2 = {"Bloodlust Brooch", "Dragonspine Trophy"},
            mainhand = "Spiteblade",
            offhand  = "Latro's Shifting Sword",
            ranged   = "Sunfury Bow of the Phoenix",
        },
    },
    ["Protection"] = {
        T4 = {
            head     = "Warbringer Greathelm",
            neck     = "Barbed Choker of Discipline",
            shoulder = "Warbringer Shoulderguards",
            back     = "Gilded Thorium Cloak",
            chest    = "Warbringer Chestguard",
            wrist    = "Bracers of the Green Fortress",
            hands    = "Iron Gauntlets of the Maiden",
            waist    = "Crimson Girdle of the Indomitable",
            legs     = "Timewarden's Leggings",
            feet     = "Boots of Elusion",
            ring1    = {"Elementium Band of the Sentry", "Ring of Unyielding Force"},
            ring2    = {"Elementium Band of the Sentry", "Ring of Unyielding Force"},
            trinket1 = {"Moroes' Lucky Pocket Watch", "Figurine - Dawnstone Crab"},
            trinket2 = {"Moroes' Lucky Pocket Watch", "Figurine - Dawnstone Crab"},
            mainhand = "King's Defender",
            offhand  = "Shield of Impenetrable Darkness",
            ranged   = "Gyro-Balanced Khorium Destroyer",
        },
    },
},

}  -- end AltTracker.BisData
